routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/books_stock', 'Admin\BookController@stock');

Route::get('/saler-wise-sale-report', 'Admin\ReportController@salerReport');
Route::get('/agent-wise-sale-report', 'Admin\ReportController@agentReport');


Route::resource('/book_types', 'Admin\\TypeController');
Route::resource('/books', 'Admin\\BookController');
Route::resource('/book_stock', 'Admin\\ShistoryController');

Route::resource('/areas', 'Admin\\AreaController');
Route::resource('/officers', 'Admin\\OfficerController');
Route::resource('/agents', 'Admin\\DistributorController');

Route::resource('/sales', 'Admin\\SaleController');

Route::get('/{any}', function ($any) {

  return Redirect::to('/');

})->where('any', '.*');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    protected $table = 'books';

    /**
    * The database primary key value.
    *
    * @var string
    */
    protected $primaryKey = 'id';

	    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
   	protected $fillable = [
   	    'name', 'subject', 'class', 'units','purches', 'sale_rate', 'status',  'content', 'type_id'
   	];

    public function type()
    {
        return $this->belongsTo(Type::class);
    }
}

app/Http/Controllers/Admin/BookController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Session;
use Redirect,Response;
use Auth;

use App\Type;
use App\Book;

class BookController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Book::all();
        return view('admin.books.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $types = Type::where('status', '=', 'Active')->get();
        return view('admin.books.create', compact('types'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $request->validate([
                'name' => ['required', 'string', 'max:255'],
                'subject'=>['required','string'],
                'class'=>['required','string'],
                'type_id'=>['required','string'],
                'sale_rate'=>['required','string'],
                'status'=>['required','string'],
                ]);

        $books = new Book();

        $books->create($request->all());

        return Redirect::route('books.index')->withSuccess('Great! New Book Add successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Book::findOrFail($id);
        return view('admin.books.show', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Book::findOrFail($id);
        $types = Type::where('status', '=', 'Active')->get();
        return view('admin.books.edit', compact('types', 'data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $request->validate([
                'name' => ['required', 'string', 'max:255'],
                'subject'=>['required','string'],
                'class'=>['required','string'],
                'type_id'=>['required','string'],
                'sale_rate'=>['required','string'],
                'status'=>['required','string'],
                ]);

        $books = Book::findOrFail($id);

        $books->update($request->all());

        return Redirect::route('books.index')->withSuccess('Great! Book Update successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }



    public function stock()
    {
        $data = Book::where('status', '=', 'Active')->get();
        return view('pages.book_stock', compact('data'));
    }
}

resources/views/admin/books/create.blade.php
@extends('layouts.main')

@section('content')


  <div class="content-wrapper">

    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-12">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Book Setup</h3>
              </div>

              <div class="row p-3">
                <div class="col-12">
                  <a class="btn btn-sm btn-success" href="{{ route('books.index') }}">Back</a>
                </div>
              </div>

              <form role="form" method="post" action="{{ route('books.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                  <div class="row">
                    <div class="col-12 col-sm-6">
                      <div class="form-group">
                          <label for="">Book Type</label>
                          <select class="form-control @error('type_id') is-invalid @enderror" name="type_id" required="required">
                            <option value="" active>Select a option</option>
                            @foreach($types as $type)
                            <option value="{{ $type->id }}">{{ $type->title }}</option>
                            @endforeach
                          </select>
                          @error('type_id')
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                          @enderror
                      </div>
                      <div class="form-group">
                        <label for="name">Book Title</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Title" required value="{{ old('name') }}" >
                      </div>
                      <div class="form-group">
                        <label for="subject">Book subject</label>
                        <input type="text" name="subject" class="form-control" id="subject" placeholder="Book subject" required value="{{ old('subject') }}" >
                      </div>
                      <div class="form-group">
                        <label for="class">Book for class</label>
                        <input type="text" name="class" class="form-control" id="class" placeholder="Book class" required value="{{ old('class') }}" >
                      </div>
                      
                      <div class="form-group">
                        <label for="content">Content</label>
                        <textarea  class="form-control" rows="3" name="content"></textarea>
                      </div>
                    </div>
                    <div class="col-12 col-sm-6">
                      <div class="form-group">
                        <label for="units">Present Stock</label>
                        <input type="text" name="units" class="form-control" id="units" placeholder="Present Stock" required value="{{ old('units') }}">
                      </div>
                      <div class="form-group">
                        <label for="purches">Purches rate</label>
                        <input type="text" name="purches" class="form-control" id="purches" placeholder="Purches rate" required value="{{ old('purches') }}">
                      </div>
                      <div class="form-group">
                        <label for="sale_rate">Sale rate</label>
                        <input type="text" name="sale_rate" class="form-control" id="sale_rate" placeholder="Sale rate" required value="{{ old('sale_rate') }}">
                      </div>
                      
                      <div class="form-group">
                          <label for="">Status</label>
                          <select class="form-control @error('status') is-invalid @enderror" name="status" required="required">
                            <option value="" active>Select a option</option>
                            <option>Active</option>
                            <option>Inactive</option>
                          </select>
                          @error('status')
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                          @enderror
                      </div>
                      
                    </div>
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>

        
      </div>
    </div>
 
  </div>

@endsection

resources/views/admin/books/edit.blade.php
@extends('layouts.main')

@section('content')


  <div class="content-wrapper">

    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-12">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Book Edit</h3>
              </div>

              <div class="row p-3">
                <div class="col-12">
                  <a class="btn btn-sm btn-success" href="{{ route('books.index') }}">Back</a>
                </div>
              </div>

              <form role="form" method="post" action="{{ route('books.update', $data->id) }}" enctype="multipart/form-data">
                @csrf
                 @method('Patch')  
                <div class="card-body">
                  <div class="row">
                    <div class="col-12 col-sm-6">
                      <div class="form-group">
                          <label for="">Book Type</label>
                          <select class="form-control @error('type_id') is-invalid @enderror" name="type_id" required="required">
                            <option value="" active>Select a option</option>
                            @foreach($types as $type)
                            <option value="{{ $type->id }}" {{ $type->id == $data->type_id ? 'selected' : '' }}>{{ $type->title }}</option>
                            @endforeach
                          </select>
                          @error('type_id')
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                          @enderror
                      </div>
                      <div class="form-group">
                        <label for="name">Book Title</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Title" required value="{{ $data->name }}" >
                      </div>
                      <div class="form-group">
                        <label for="subject">Book subject</label>
                        <input type="text" name="subject" class="form-control" id="subject" placeholder="Book subject" required value="{{ $data->subject }}" >
                      </div>
                      <div class="form-group">
                        <label for="class">Book for class</label>
                        <input type="text" name="class" class="form-control" id="class" placeholder="Book class" required value="{{ $data->class }}" >
                      </div>
                      
                      <div class="form-group">
                        <label for="content">Content</label>
                        <textarea  class="form-control" rows="3" name="content">{{ $data->content }}</textarea>
                      </div>
                    </div>
                    <div class="col-12 col-sm-6">
                      <div class="form-group">
                        <label for="units">Present Stock</label>
                        <input type="text" name="units" class="form-control" id="units" placeholder="Present Stock" required value="{{ $data->units }}">
                      </div>
                      <div class="form-group">
                        <label for="purches">Purches rate</label>
                        <input type="text" name="purches" class="form-control" id="purches" placeholder="Purches rate" required value="{{ $data->purches }}">
                      </div>
                      <div class="form-group">
                        <label for="sale_rate">Sale rate</label>
                        <input type="text" name="sale_rate" class="form-control" id="sale_rate" placeholder="Sale rate" required value="{{ $data->sale_rate }}">
                      </div>
                      
                      <div class="form-group">
                          <label for="">Status</label>
                          <select class="form-control @error('status') is-invalid @enderror" name="status" required="required">
                            <option value="" active>Select a option</option>
                            <option {{ $data->status == 'Active' ? 'selected' : '' }}>Active</option>
                            <option {{ $data->status == 'Inactive' ? 'selected' : '' }}>Inactive</option>
                          </select>
                          @error('status')
                              <span class="invalid-feedback" role="alert">
                                  <strong>{{ $message }}</strong>
                              </span>
                          @enderror
                      </div>
                      
                    </div>
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Update</button>
                </div>
              </form>
            </div>
          </div>
        </div>

        
      </div>
    </div>
 
  </div>

@endsection

resources/views/admin/books/index.blade.php
@extends('layouts.main')
@section('content')
<div class="content-wrapper">
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-12 col-sm-10">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Books List</h3>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-12">
                  <a class="btn btn-sm btn-success" href="{{ route('books.create') }}">Add New</a>
                </div>
              </div>
              
              @if ($message = Session::get('success'))
              <hr>
              <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
              </div>
              <br>
              <hr>
              @endif
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Sl.</th>
                    <th>Type Title</th>
                    <th>Book Name</th>
                    <th>Subject</th>
                    <th>Preasent Stock</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($data as $item)
                    <tr>
                      <td>{{ $loop->iteration }}</td>
                      <td>{{ $item->type->title }}</td>
                      <td>{{ $item->name }}</td>
                      <td>{{ $item->subject }}</td>
                      <td>{{ $item->units }}</td>
                      <td>{{ $item->status }}</td>
                      <td>
                        <a class="btn btn-sm btn-primary" href="{{ route('books.show', $item->id) }}">Show</a>
                        <a class="btn btn-sm btn-danger" href="{{ route('books.edit', $item->id) }}">Edit</a>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
               
                
              </table>
            </div>
          </div>
        </div>
      </div>
      
    </div>
  </div>
  
</div>
@endsection
@section('java_script')
<script>
$(function () {
$("#example1").DataTable();
$('#example2').DataTable({
"paging": true,
"lengthChange": false,
"searching": false,
"ordering": true,
"info": true,
"autoWidth": false,
});
});
</script>
@endsection

resources/views/admin/books/show.blade.php
@extends('layouts.main')
@section('content')
<div class="content-wrapper">
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-12 col-sm-8">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Book Details</h3>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-12">
                  <a class="btn btn-sm btn-success my-3" href="{{ route('books.index') }}">Back</a>
                </div>
              </div>
              
              @if ($message = Session::get('success'))
              <hr>
              <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
              </div>
              <br>
              <hr>
              @endif
              <table class="table table-bordered table-striped">
                <tr>
                  <th>Book Type</th>
                  <td>{{  $data->type->title }}</td>
                </tr>
                <tr>
                  <th>Book Name</th>
                  <td>{{  $data->name }}</td>
                </tr>
                <tr>
                  <th>Book for class</th>
                  <td>{{  $data->class }}</td>
                </tr>
                <tr>
                  <th>Book purches rate</th>
                  <td>{{  $data->purches }}</td>
                </tr>
                <tr>
                  <th>Book sale rate</th>
                  <td>{{  $data->sale_rate}}</td>
                </tr>
                <tr>
                  <th>Book Present stock</th>
                  <td>{{  $data->units}}</td>
                </tr>
                <tr>
                  <th>Status</th>
                  <td>{{  $data->status}}</td>
                </tr>
                <tr>
                  <th>Content</th>
                  <td>{{  $data->content}}</td>
                </tr>
                
              </table>
            </div>
          </div>
        </div>
      </div>
      
    </div>
  </div>
  
</div>
@endsection