routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/books_stock', 'Admin\BookController@stock');

Route::get('/saler-wise-sale-report', 'Admin\ReportController@salerReport');
Route::get('/agent-wise-sale-report', 'Admin\ReportController@agentReport');


Route::resource('/book_types', 'Admin\\TypeController');
Route::resource('/books', 'Admin\\BookController');
Route::resource('/book_stock', 'Admin\\ShistoryController');

Route::resource('/areas', 'Admin\\AreaController');
Route::resource('/officers', 'Admin\\OfficerController');
Route::resource('/agents', 'Admin\\DistributorController');

Route::resource('/sales', 'Admin\\SaleController');

Route::get('/{any}', function ($any) {

  return Redirect::to('/');

})->where('any', '.*');

app/Area.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Area extends Model
{
     protected $table = 'areas';

     /**
     * The database primary key value.
     *
     * @var string
     */
     protected $primaryKey = 'id';

 	    /**
      * Attributes that should be mass-assignable.
      *
      * @var array
      */
    	protected $fillable = [
    	    'name', 'district', 'division', 'content', 'status'
    	];

    public function officer()
    {
        return $this->hasMany(Officer::class);
    }
    
    public function agent()
    {
        return $this->hasMany(Agent::class);
    }
}

app/Http/Controllers/Admin/AreaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Session;
use Redirect,Response;
use Auth;

use App\Area;

class AreaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Area::all();
        return view('admin.area.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.area.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
                'name' => ['required', 'string', 'max:255'],
                'district'=>['required','string'],
                'status'=>['required','string'],
                ]);

        $areas = new Area();

        $areas->create($request->all());

        return Redirect::route('areas.index')->withSuccess('Great! New Territory Area Add successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Area::findOrFail($id);
        return view('admin.area.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
         $request->validate([
                'name' => ['required', 'string', 'max:255'],
                'district'=>['required','string'],
                'status'=>['required','string'],
                ]);

        $area = Area::findOrFail($id);

        $area->update($request->all());

        return Redirect::route('areas.index')->withSuccess('Great! Book Update successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/area/create.blade.php
@extends('layouts.main')

@section('content')


  <div class="content-wrapper">

    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-12 col-sm-6">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Territory Area Setup</h3>
              </div>

              <div class="row">
                <div class="col-12">
                  <a class="btn btn-sm btn-success m-3" href="{{ route('book_types.index') }}">Back</a>
                </div>
              </div>

              <form role="form" method="post" action="{{ route('areas.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                      <label for="">Division Name</label>
                      <select class="form-control @error('division') is-invalid @enderror" name="division" required="required">
                        <option value="" active>Select a option</option>
                        <option>Barishal</option>
                        <option>Chittagong</option>
                        <option>Dhaka</option>
                        <option>Mymensingh</option>
                        <option>Khulna</option>
                        <option>Rajshahi</option>
                        <option>Rangpur</option>
                        <option>Sylhet</option>
                      </select>
                      @error('division')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                      @enderror
                  </div>
                  <div class="form-group">
                    <label for="district">District Name</label>
                    <input type="text" name="district" class="form-control" id="district" placeholder="District Name" required>
                  </div>
                  <div class="form-group">
                    <label for="title">Territory Area Name</label>
                    <input type="text" name="name" class="form-control" id="title" placeholder="Area Name" required>
                  </div>
                  
                  <div class="form-group">
                      <label for="">Status</label>
                      <select class="form-control @error('status') is-invalid @enderror" name="status" required="required">
                        <option value="" active>Select a option</option>
                        <option>Active</option>
                        <option>Inactive</option>
                      </select>
                      @error('status')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                      @enderror
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>

        
      </div>
    </div>
 
  </div>

@endsection

resources/views/admin/area/edit.blade.php
@extends('layouts.main')

@section('content')


  <div class="content-wrapper">

    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-12 col-sm-6">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Territory Area Update</h3>
              </div>

              <div class="row">
                <div class="col-12">
                  <a class="btn btn-sm btn-success m-3" href="{{ route('areas.index') }}">Back</a>
                </div>
              </div>

              <form role="form" method="post" action="{{ route('areas.update',$data->id) }}" enctype="multipart/form-data">
                @csrf
                @method('Patch') 
                <div class="card-body">
                  <div class="form-group">
                      <label for="">Division Name</label>
                      <select class="form-control @error('division') is-invalid @enderror" name="division" required="required">
                        <option value="" active>Select a option</option>
                        <option {{ $data->division == 'Barishal' ? 'Selected' : '' }}>Barishal</option>
                        <option {{ $data->division == 'Chittagong' ? 'Selected' : '' }}>Chittagong</option>
                        <option {{ $data->division == 'Dhaka' ? 'Selected' : '' }}>Dhaka</option>
                        <option {{ $data->division == 'Mymensingh' ? 'Selected' : '' }}>Mymensingh</option>
                        <option {{ $data->division == 'Khulna' ? 'Selected' : '' }}>Khulna</option>
                        <option {{ $data->division == 'Rajshahi' ? 'Selected' : '' }}>Rajshahi</option>
                        <option {{ $data->division == 'Rangpur' ? 'Selected' : '' }}>Rangpur</option>
                        <option {{ $data->division == 'Sylhet' ? 'Selected' : '' }}>Sylhet</option>
                      </select>
                      @error('division')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                      @enderror
                  </div>
                  <div class="form-group">
                    <label for="district">District Name</label>
                    <input type="text" name="district" class="form-control" id="district" value="{{ $data->district }}" required>
                  </div>
                  <div class="form-group">
                    <label for="title">Territory Area Name</label>
                    <input type="text" name="name" class="form-control" id="title" value="{{ $data->name }}" required>
                  </div>
                  
                  <div class="form-group">
                      <label for="">Status</label>
                      <select class="form-control @error('status') is-invalid @enderror" name="status" required="required">
                        <option value="" active>Select a option</option>
                        <option {{ $data->status == 'Active' ? 'selected' : '' }}>Active</option>
                        <option {{ $data->status == 'Inactive' ? 'selected' : '' }}>Inactive</option>
                      </select>
                      @error('status')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                      @enderror
                  </div>
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Update</button>
                </div>
              </form>
            </div>
          </div>
        </div>

        
      </div>
    </div>
 
  </div>

@endsection

resources/views/admin/area/index.blade.php
@extends('layouts.main')
@section('content')
<div class="content-wrapper">
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-12 col-sm-10">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Territory Area List</h3>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-12">
                  <a class="btn btn-sm btn-success" href="{{ route('areas.create') }}">Add New</a>
                </div>
              </div>
              
              @if ($message = Session::get('success'))
              <hr>
              <div class="alert alert-success alert-block">
                <button type="button" class="close" data-dismiss="alert">×</button>
                <strong>{{ $message }}</strong>
              </div>
              <br>
              <hr>
              @endif
              <table id="example1" class="table table-bordered table-striped">
                <thead>
                  <tr>
                    <th>Sl.</th>
                    <th>Division Name</th>
                    <th>District Name</th>
                    <th>Territory Area Name</th>
                    <th>Status</th>
                    <th>Action</th>
                  </tr>
                </thead>
                <tbody>
                  @foreach($data as $item)
                    <tr>
                      <td>{{ $loop->iteration }}</td>
                      <td>{{ $item->name }}</td>
                      <td>{{ $item->division }}</td>
                      <td>{{ $item->district }}</td>
                      <td>{{ $item->status }}</td>
                      <td>
                        <a class="btn btn-sm btn-danger" href="{{ route('areas.edit', $item->id) }}">Edit</a>
                      </td>
                    </tr>
                  @endforeach
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
      
    </div>
  </div>
  
</div>
@endsection
@section('java_script')
<script>
$(function () {
$("#example1").DataTable();
$('#example2').DataTable({
"paging": true,
"lengthChange": false,
"searching": false,
"ordering": true,
"info": true,
"autoWidth": false,
});
});
</script>
@endsection