routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/books_stock', 'Admin\BookController@stock');

Route::get('/saler-wise-sale-report', 'Admin\ReportController@salerReport');
Route::get('/agent-wise-sale-report', 'Admin\ReportController@agentReport');


Route::resource('/book_types', 'Admin\\TypeController');
Route::resource('/books', 'Admin\\BookController');
Route::resource('/book_stock', 'Admin\\ShistoryController');

Route::resource('/areas', 'Admin\\AreaController');
Route::resource('/officers', 'Admin\\OfficerController');
Route::resource('/agents', 'Admin\\DistributorController');

Route::resource('/sales', 'Admin\\SaleController');

Route::get('/{any}', function ($any) {

  return Redirect::to('/');

})->where('any', '.*');

app/Http/Controllers/Admin/TypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

use Session;
use Redirect,Response;
use Auth;

use App\Type;

class TypeController extends Controller
{

	public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Type::all();
        return view('admin.types.index', compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.types.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request);
        $request->validate([
                'title' => ['required', 'string', 'max:255'],
                'status'=>['required','string'],
                ]);

        $types = new Type();

        $types->create($request->all());

        return Redirect::route('book_types.index')->withSuccess('Great! New Book Type Add successfully.');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Type::findOrFail($id);
        return view('admin.types.edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
                'title' => ['required', 'string', 'max:255'],
                'status'=>['required','string'],
                ]);
        $types = Type::findOrFail($id);
        $types->update($request->all());

        return Redirect::route('book_types.index')->withSuccess('Great! Book Type edit successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/types/create.blade.php
@extends('layouts.main')

@section('content')


  <div class="content-wrapper">

    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-12 col-sm-6">
            <div class="card card-primary">
              <div class="card-header">
                <h3 class="card-title">Book Type Setup</h3>
              </div>

              <div class="row">
                <div class="col-12">
                  <a class="btn btn-sm btn-success p-3" href="{{ route('book_types.index') }}">Back</a>
                </div>
              </div>

              <form role="form" method="post" action="{{ route('book_types.store') }}" enctype="multipart/form-data">
                @csrf
                <div class="card-body">
                  <div class="form-group">
                    <label for="title">Type Title</label>
                    <input type="text" name="title" class="form-control" id="title" placeholder="Title">
                  </div>
                  
                  <div class="form-group">
                      <label for="">Status</label>
                      <select class="form-control @error('status') is-invalid @enderror" name="status" required="required">
                        <option value="" active>Select a option</option>
                        <option>Active</option>
                        <option>Inactive</option>
                      </select>
                      @error('status')
                          <span class="invalid-feedback" role="alert">
                              <strong>{{ $message }}</strong>
                          </span>
                      @enderror
                  </div>
                  <div class="form-group">
                    <label for="content">Content</label>
                    <textarea  class="form-control" rows="5" name="content"></textarea>
                </div>
                  
                </div>
                <!-- /.card-body -->

                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Submit</button>
                </div>
              </form>
            </div>
          </div>
        </div>

        
      </div>
    </div>
 
  </div>

@endsection

resources/views/admin/types/edit.blade.php
@extends('layouts.main')
@section('content')
<div class="content-wrapper">
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-12 col-sm-6">
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Book Type Edit</h3>
            </div>
            <div class="card-body">
              <div class="row">
                <div class="col-12">
                  <a class="btn btn-sm btn-success" href="{{ route('book_types.index') }}">Back</a>
                </div>
              </div>
              <form role="form" method="post" action="{{ route('book_types.update', $data->id) }}" enctype="multipart/form-data">
                @csrf
                @method('Patch')  
                <div class="card-body">
                  <div class="form-group">
                    <label for="title">Type Title</label>
                    <input type="text" name="title" class="form-control" id="title" value="{{ $data->title }}">
                  </div>
                  
                  <div class="form-group">
                    <label for="">Status</label>
                    <select class="form-control @error('status') is-invalid @enderror" name="status" required="required">
                      <option value="" active>Select a option</option>
                      <option {{ $data->status == 'Active' ? 'selected' : '' }}>Active</option>
                      <option {{ $data->status == 'Inactive' ? 'selected' : '' }}>Inactive</option>
                    </select>
                    @error('status')
                    <span class="invalid-feedback" role="alert">
                      <strong>{{ $message }}</strong>
                    </span>
                    @enderror
                  </div>
                  <div class="form-group">
                    <label for="content">Content</label>
                    <textarea  class="form-control" rows="5" name="content">{{ $data->content }}</textarea>
                  </div>
                  
                </div>
                <!-- /.card-body -->
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Update</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
      
    </div>
  </div>
  
</div>
@endsection